### ISSUE TITLE
jabber.org service, website, announcements etc

### ISSUE THREAD

**Issue by Neustradamus** [stpeter/jabberdotorg#1]
Jabber.org is managed by volunteers like we can read on the main page: https://www.jabber.org/ with a link to https://www.jabber.org/team.html.

We can note:
- The mailing list is abandoned (mail must be validated): https://mail.jabber.org/mailman/listinfo/juser
- No news since 2014 on https://www.jabber.org/notices.html
- No news since 2013 https://identi.ca/jabberdotorg, can be removed? (not used since migration of StatusNet to Pumpio)
- There are some news but not all: https://twitter.com/jabberdotorg
- No announcements about crashs (Web, XMPP, etc), changes like certificate, ...
- When the XMPP certificate is expired and when we inform directly, no reply
- When we inform team on jabber@conference.jabber.org (it is not us...), maybe time to update the team page?
- When a person requests a password reset, no reply (example @camaran)
- No ticket tracking

**Comment by stpeter** [comment]
Closing here because I replied on the JUser list:

https://mail.jabber.org/pipermail/juser/2018-May/007163.html

Peter

**Comment by Neustradamus** [comment]
> As posted to https://github.com/stpeter/jabberdotorg/issues/1 ...
>
> On 3/29/18 10:16 AM, Neustradamus wrote:
>> Jabber.org is managed by volunteers like we can read on the main page:
>> https://www.jabber.org/ with a link to https://www.jabber.org/team.html.
>>
>> We can note:
>>
>>   * The mailing list is abandoned (mail must be validated):
>>     https://mail.jabber.org/mailman/listinfo/juser
>
> Who says the list is abandoned? There is discussion, just not very frequent:
>
> https://mail.jabber.org/pipermail/juser/
>
>>   * No news since 2014 on https://www.jabber.org/notices.html
>
> Nothing to report.

Crashs, DDOS attacks, team changes, certificates renews, server updates, ...


>>   * No news since 2013 https://identi.ca/jabberdotorg, can be removed?
>>     (not used since migration of StatusNet to Pumpio)
>
> Yes, I'll delete that account.

Good, inform us when it is done ^^


>>   * There are some news but not all: https://twitter.com/jabberdotorg
>
> I did change the account password yesterday, though.

Yes Twitter has requested password changes.


>>   * No announcements about crashs (Web, XMPP, etc), changes like
>>     certificat, ...
>
> Certificates change frequently, via Let's Encrypt. Doesn't seem worth an
> announcement.

It is important to communicate.


>>   * When the XMPP certificat is expired and when we inform directly, no
>>     reply
>
> Expired certificates have been taken care of quite quickly, no?

Since several years maybe it is better, but when we inform on the mucroom "it is not us", team page must be updated?


>>   * When we inform team on jabber@conference.jabber.org
>>     <mailto:jabber@conference.jabber.org> (it is not us...), maybe time
>>     to update the team page?
>
> I'll admit I don't hang out there all the time.

There is a team no? https://www.jabber.org/team.html
To be updated?


>>   * When a person requests a password reset, no reply (example @camaran
>>     <https://github.com/camaran>)
>
> Over the last year I have responded to hundreds, perhaps thousands, of
> password requests. Sorry if I missed a few.

A friend who has sent a message in 2013 had a reply few week ago, after 5 years!

Have you replied to @camaran?
Because he said me again today no reply...


>>   * No ticket tracking
>
> Feel free to post to the list here.
>
> Peter

**Comment by Neustradamus** [comment]
Any news @stpeter?
Have you read my previous comment?

**Comment by Neustradamus** [comment]
Need an update about team?

https://www.jabber.org/team.html : People on github + Jonathan Siegle
@stpeter @Kev @mwild1 @intosi

There are problems not resolved since a long time.
