### ISSUE TITLE
Invalid (expired) cert 

### ISSUE THREAD

**Issue by mdosch** [stpeter/jabberdotorg#15]
Establishing a secure connection from mdosch.de to jabber.org failed. Certificate hash: c069b1a830d5e6d05a662648eae6f4e03de17e36658af1a33be3d88a3217c943. Error with certificate 0: certificate has expired.

**Comment by stpeter** [comment]
Hmm, that's strange, we renewed the cert. I'll take a look.

**Comment by mdosch** [comment]
Two persons in xmpp@chat.yax.im confirmed it is expired.

**Comment by stpeter** [comment]
Fixed. We had to fiddle with some symlinks on the machine.
