### ISSUE TITLE
jabber.org can not join good XMPP secured servers

### ISSUE THREAD

**Issue by Neustradamus** [stpeter/jabberdotorg#21]
The jabber.org XMPP server can not join good XMPP secured servers.

Example:
- xmpp.org

Linked to:
- https://github.com/stpeter/jabberdotorg/issues/3
- https://github.com/stpeter/jabberdotorg/issues/6

**Comment by stpeter** [comment]
KNOWN ISSUE.

**Comment by Neustradamus** [comment]
@stpeter: Yes but it is not needed to close an unsolved issue :)

**Comment by stpeter** [comment]
As I have said repeatedly, we're working on it and will provide an update on the website once this is all fixed. (Yes, I know that the website is down right now - we're working on THAT too.)

**Comment by Neustradamus** [comment]
@stpeter: I wish you a happy new year!

Any news about the migration?
This ticket is closed, I can create a new?

Thanks in advance.

**Comment by mwild1** [comment]
> Any news about the migration?

As Peter said in his last comment, news will be posted when there is news.

> This ticket is closed, I can create a new?

No, thank you.

**Comment by Neustradamus** [comment]
Hi all,

The problem is always here (2023-01-02), can you reopen this ticket?

For example, you can see a message on the mailinglist here:
- https://mail.jabber.org/pipermail/juser/2022-August/007188.html
